require("dotenv").config();
const bcrypt = require("bcryptjs");
const { v4: uuidv4 } = require("uuid");
const db = require("./db");

const gdrive = (id) => `https://drive.google.com/thumbnail?id=${id}&sz=w800`;

const ENTRIES = [
  { label: "Birth Day", age: "Day 0", date: "25 April 2022", photo: gdrive("1xJUA_bpR-WKPsUGkRrNpuebfqcW_oawl"), caption: "Welcome to the world, little Alysha! 🌸", milestone: "First breath of life", ageInDays: 0, location: "হাজারীবাগ, ঢাকা" },
{ label: "3 Wks", age: "3 weeks", date: "13 May 2022", photo: gdrive("1wp7d6llb-djdyQUi7R_VKEKxbzwrEvnL"), caption: "Learning what this beautiful world is all about", milestone: "Newborn wonder", ageInDays: 18 },
  { label: "4 Wks", age: "4 weeks", date: "23 May 2022", photo: gdrive("1ut_4h0u2e5br64XaEs-LWN_rDY8gT1Yd"), caption: "Learning what this beautiful world is all about", milestone: "Newborn wonder", ageInDays: 28 },
  { label: "1 Mo", age: "~1 months", date: "4 June 2022", photo: gdrive("1y52hNTE0OEVxP9a6n1IyuarjLZSnDkjv"), caption: "That smile makes every heart melt 💕", milestone: "Social smiling", ageInDays: 40 },
  { label: "2 Mo", age: "~2 months", date: "10 June 2022", photo: gdrive("1_iSlugaucz7RnTwZqXMk04rWmC8W29oT"), caption: "That smile makes every heart melt 💕", milestone: "Social smiling", ageInDays: 46, location: "ধানমন্ডি, ঢাকা" },
  { label: "2 Mo", age: "~2 months", date: "19 June 2022", photo: gdrive("1pNyqVWkiYO3lZb5BpsMVW3_IT0G-3Mi2"), caption: "That smile makes every heart melt 💕", milestone: "Social smiling", ageInDays: 55 },
  { label: "2 Mo", age: "~2 months", date: "29 June 2022", photo: gdrive("1PPGCLhFdLrmaJQ9jL1TG-hJGoXKJ62vU"), caption: "Growing stronger and more beautiful every day", milestone: "Cooing & tracking", ageInDays: 65, location: "মিরপুর সেনানিবাস, ঢাকা" },
  { label: "2 Mo", age: "~2 months", date: "2 July 2022", photo: gdrive("10SLGZK_m3PPgC1cEnHmYdvC0nfjCFCUF"), caption: "Growing stronger and more beautiful every day", milestone: "Cooing & tracking", ageInDays: 68, location: "মিরপুর সেনানিবাস, ঢাকা" },
  { label: "2 Mo", age: "~2 months", date: "2 July 2022", photo: gdrive("1E2Z13565nAf726wo4JfzBm0TBS6Djuey"), caption: "Growing stronger and more beautiful every day", milestone: "Cooing & tracking", ageInDays: 68, location: "মিরপুর সেনানিবাস, ঢাকা" },
  { label: "2 Mo", age: "~2 months", date: "6 July 2022", photo: gdrive("1kMmILdAZiD460JFc1lKQGQvfQ8LsKrYG"), caption: "Growing stronger and more beautiful every day", milestone: "Cooing & tracking", ageInDays: 72 },
  { label: "2 Mo", age: "~2 months", date: "8 July 2022", photo: gdrive("1gteJUmDXwYZzLqL9LApYwZ8a0TAkigOz"), caption: "Growing stronger and more beautiful every day", milestone: "Cooing & tracking", ageInDays: 74, location: "পল্লবী, ঢাকা" },
  { label: "3 Mo", age: "~3 months", date: "22 July 2022", photo: gdrive("1Q3o1QatoUFHZC7n3e1uUKiQz-f7-tfA9"), caption: "Growing stronger and more beautiful every day", milestone: "Cooing & tracking", ageInDays: 88, location: "পল্লবী, ঢাকা" },
  { label: "3 Mo", age: "~3 months", date: "22 July 2022", photo: gdrive("1PRE0DTP9J1SZ8VMpjVrNW_t82sMP6M0m"), caption: "Growing stronger and more beautiful every day", milestone: "Cooing & tracking", ageInDays: 88, location: "পল্লবী, ঢাকা" },
  { label: "3 Mo", age: "~3 months", date: "29 July 2022", photo: gdrive("1S0LPKgg5CrC36iGmrHn6oB6rN-7oEFAK"), caption: "Curious eyes discovering everything around her", milestone: "Head control", ageInDays: 95 },
  { label: "4 Mo", age: "~4 months", date: "18 August 2022", photo: gdrive("1UR5vc9OxBdYk7rbOWXiA6JJL3CNeKedP"), caption: "Curious eyes discovering everything around her", milestone: "Head control", ageInDays: 115 },
  { label: "5 Mo", age: "~5 months", date: "12 September 2022", photo: gdrive("1dWg1OFh90koge6OkWCzqlFYL6fkSc_1K"), caption: "Curious eyes discovering everything around her", milestone: "Reaching & grasping", ageInDays: 140 },
  { label: "6 Mo", age: "~6 months", date: "7 October 2022", photo: gdrive("11ZLGZ7xrai9uwaTFt08y7cYeSM2r4NA-"), caption: "Curious eyes discovering everything around her", milestone: "Reaching & grasping", ageInDays: 165 },
  { label: "6 Mo", age: "~6 months", date: "1 November 2022", photo: gdrive("1pbThEjV6jycSZpcUdjVnSWjn8N1URlKc"), caption: "Exploring and discovering her world", milestone: "Sitting up", ageInDays: 190 },
  { label: "7 Mo", age: "~7 months", date: "1 December 2022", photo: gdrive("1r0CqwsWj1u8luRmR-oNIfsZ2XsxBuL_X"), caption: "Exploring and discovering her world", milestone: "Sitting up", ageInDays: 220 },
  { label: "1y 1m", age: "1 yr 1 mo", date: "11 May 2023", photo: gdrive("1mM1y7Cv_1z6phRI2B3t3B3wiZG5MLX-f"), caption: "Every day is a new adventure!", milestone: "Toddler curiosity", ageInDays: 381 },
  { label: "1y 1m", age: "1 yr 1 mo", date: "27 May 2023", photo: gdrive("1m2Rq2fHUZnAa8AhOgk9XhaeaqBUibOBE"), caption: "Every day is a new adventure!", milestone: "Toddler curiosity", ageInDays: 397 },
  { label: "1y 2m", age: "1 yr 2 mo", date: "29 June 2023", photo: gdrive("1lx26_0VJgkZ-sadYk6R7QkGrsAo8R5O3"), caption: "Every day is a new adventure!", milestone: "Toddler curiosity", ageInDays: 430 },
  { label: "1y 2m", age: "1 yr 2 mo", date: "14 July 2023", photo: gdrive("1lLlgyvoHF1N7Byy-T2HeLbxA2-3sCR3C"), caption: "Every day is a new adventure!", milestone: "Toddler curiosity", ageInDays: 445 },
  { label: "1y 2m", age: "1 yr 2 mo", date: "22 July 2023", photo: gdrive("1kdw0x9btw2cpsVf6zdbBiqJ-qRjBVB-U"), caption: "Every day is a new adventure!", milestone: "Toddler curiosity", ageInDays: 453 },
  { label: "1y 4m", age: "1 yr 4 mo", date: "29 August 2023", photo: gdrive("1hUqMzl0khLr16ocvCAqWnotKdi17YTqY"), caption: "Every day is a new adventure!", milestone: "Toddler curiosity", ageInDays: 491 },
  { label: "1y 4m", age: "1 yr 4 mo", date: "15 September 2023", photo: gdrive("1hCCRpItwPh9NsvxWLPpuKV-WxvBtND2c"), caption: "Every day is a new adventure!", milestone: "Toddler curiosity", ageInDays: 508 },
  { label: "1y 6m", age: "1 yr 6 mo", date: "23 October 2023", photo: gdrive("1pRMetaF4H9BD2cY-AxMtmlkFsat9Z6zq"), caption: "Toddler adventures begin!", milestone: "First steps!", ageInDays: 546 },
  { label: "2yr", age: "2 years", date: "27 April 2024", photo: gdrive("1cMW_iq3nJohFEq58sY7rSEx_uxsm8YyC"), caption: "Happy 2nd Birthday Alysha! 🎂", milestone: "2nd Birthday!", ageInDays: 733, location: "রাজাবাড়ী, শ্রীপুর উপজেলা (গাজীপুর)" },
  { label: "2yr", age: "2 years", date: "27 April 2024", photo: gdrive("1SNQCBOd7Q4BP5qKmTqNLbZM5XhDnWc3W"), caption: "Two years of pure joy and wonder!", milestone: "2nd Birthday!", ageInDays: 733, location: "রাজাবাড়ী, শ্রীপুর উপজেলা (গাজীপুর)" },
  { label: "2yr", age: "2 years", date: "5 May 2024", photo: gdrive("11gnmLbDrNJiNlYCzpIxrkw9Z0aHIUR9Z"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 741, location: "হাজারীবাগ, ঢাকা" },
  { label: "2yr", age: "2 years", date: "6 May 2024", photo: gdrive("1kkoXda1XSDbr26wq3measgNvlVIFP2XT"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 742, location: "হাজারীবাগ, ঢাকা" },
  { label: "2yr", age: "2 years", date: "15 May 2024", photo: gdrive("1txcWXFZnqbBtrvVU3fOndYT-M3k9iANh"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 751, location: "মোহাম্মদপুর, ঢাকা" },
  { label: "2y 1m", age: "2 yr 1 mo", date: "4 June 2024", photo: gdrive("1jMXl7v52dJP8cgxM9JiPV2SXdUPSMXxP"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 771, location: "গুলশান, ঢাকা" },
  { label: "2y 1m", age: "2 yr 1 mo", date: "5 June 2024", photo: gdrive("1flkpLiqP6miZjzW0SFCj5T-MT6AJOBzf"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 772, location: "গুলশান, ঢাকা" },
  { label: "2y 2m", age: "2 yr 2 mo", date: "23 June 2024", photo: gdrive("1EFVeCrgEV43CyMcWvrtjlzjNNrW6XpN2"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 790, location: "ভুলতা, রূপগঞ্জ উপজেলা" },
  { label: "2y 2m", age: "2 yr 2 mo", date: "29 June 2024", photo: gdrive("1xJyFpmAVFPaV4_Fl1TOOwu3aZLb6fu96"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 796, location: "ভুলতা, রূপগঞ্জ উপজেলা" },
  { label: "2y 2m", age: "2 yr 2 mo", date: "30 June 2024", photo: gdrive("1aWFpqQVBdPDxkoe1qDdTzk_OPF6EfgZP"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 797, location: "ভুলতা, রূপগঞ্জ উপজেলা" },
  { label: "2y 2m", age: "2 yr 2 mo", date: "18 July 2024", photo: gdrive("15OZ7Ej5FF9oHgt6_fWKJxiqc2swLM16a"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 815, location: "কাফরুল, ঢাকা" },
  { label: "2y 2m", age: "2 yr 2 mo", date: "22 July 2024", photo: gdrive("1GtkQBSfE3jt0oSBpUM1VpWck-5Cqe9y5"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 819, location: "বসুন্ধরা আবাসিক এলাকা, ঢাকা" },
  { label: "2y 2m", age: "2 yr 2 mo", date: "22 July 2024", photo: gdrive("1aWUXNn3ybm3TpMQMc0k5OJILpsw8wglW"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 819, location: "বসুন্ধরা আবাসিক এলাকা, ঢাকা" },
  { label: "2y 2m", age: "2 yr 2 mo", date: "22 July 2024", photo: gdrive("1pmOQE_MgERlqDxoIdwXAkdQyOztIfLyM"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 819, location: "বসুন্ধরা আবাসিক এলাকা, ঢাকা" },
  { label: "2y 3m", age: "2 yr 3 mo", date: "25 July 2024", photo: gdrive("1WWmOeDNeUndZWjRFxKfj6PnDSjvWEts6"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 822, location: "বসুন্ধরা আবাসিক এলাকা, ঢাকা" },
  { label: "2y 3m", age: "2 yr 3 mo", date: "29 July 2024", photo: gdrive("1ZlligfkR7BswC3WvSe1P85NsA_TdPRCZ"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 826, location: "কাফরুল, ঢাকা" },
  { label: "2y 3m", age: "2 yr 3 mo", date: "10 August 2024", photo: gdrive("1YVBJh4IphDO4in8RgpbjvBM4hCpaXygS"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 838, location: "ঢাকা সেনানিবাস, ঢাকা" },
  { label: "2y 3m", age: "2 yr 3 mo", date: "13 August 2024", photo: gdrive("15pQoWwX3hH0RWsy9oCBs95s5tuBHNJ8B"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 841, location: "ঢাকা সেনানিবাস, ঢাকা" },
  { label: "2y 3m", age: "2 yr 3 mo", date: "14 August 2024", photo: gdrive("1yMEwwywyWy1r8cjTHOMkuQF-i4EodA7y"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 842, location: "ঢাকা সেনানিবাস, ঢাকা" },
  { label: "2y 3m", age: "2 yr 3 mo", date: "17 August 2024", photo: gdrive("1Fa4uZh65dy1U9kRPxC4DYXqIBbiA76u9"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 845, location: "নাখালপাড়া, ঢাকা" },
  { label: "2y 4m", age: "2 yr 4 mo", date: "28 August 2024", photo: gdrive("189qoTwE-nx-gFmCre3AIdSPM2rGIQX8n"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 856, location: "জোয়ার সাহারা, ঢাকা" },
  { label: "2y 4m", age: "2 yr 4 mo", date: "8 September 2024", photo: gdrive("1OnX-RHYVuucq2iizUJinmqaujgYxsVlE"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 867, location: "ঢাকা সেনানিবাস, ঢাকা" },
  { label: "2y 4m", age: "2 yr 4 mo", date: "9 September 2024", photo: gdrive("1FOSbFa3uAjKTojwn1nvIAdt_6vj6xLw2"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 868, location: "ঢাকা সেনানিবাস, ঢাকা" },
  { label: "2y 4m", age: "2 yr 4 mo", date: "17 September 2024", photo: gdrive("1GfpCBWDGlYFn8g2IQ6Hlj--4bpAHr1QJ"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 876, location: "ঢাকা সেনানিবাস, ঢাকা" },
  { label: "2y 4m", age: "2 yr 4 mo", date: "18 September 2024", photo: gdrive("1y6QGtcznKeuz67DToJEsgoIKydaDVkBO"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 877, location: "ঢাকা সেনানিবাস, ঢাকা" },
  { label: "2y 4m", age: "2 yr 4 mo", date: "19 September 2024", photo: gdrive("1KVurB5EKK0FaWZ1q2EiEz4QzcJV64-2s"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 878, location: "ঢাকা সেনানিবাস, ঢাকা" },
  { label: "2y 5m", age: "2 yr 5 mo", date: "23 September 2024", photo: gdrive("14mjuPFeTqGThRDddiWASh_LH7H7g4JEo"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 882, location: "কাফরুল, ঢাকা" },
  { label: "2y 5m", age: "2 yr 5 mo", date: "15 October 2024", photo: gdrive("1Pipi2MdxJDp3a52qvE07z08jWEzfbdaP"), caption: "Running everywhere and talking non-stop", milestone: "Running & talking", ageInDays: 904, location: "কাফরুল, ঢাকা" },
  { label: "2y 6m", age: "2 yr 6 mo", date: "10 November 2024", photo: gdrive("158Db7v13Dm_3VIAcNUigbkQLAbnUPp_2"), caption: "Every day a new discovery and a new wonder", milestone: "Imagination blooms", ageInDays: 930, location: "কাফরুল, ঢাকা" },
  { label: "2y 6m", age: "2 yr 6 mo", date: "20 November 2024", photo: gdrive("1yl6_3KQOFhry2yuP0UyofcZrSOdlO6nC"), caption: "Every day a new discovery and a new wonder", milestone: "Imagination blooms", ageInDays: 940, location: "কাফরুল, ঢাকা" },
  { label: "2y 7m", age: "2 yr 7 mo", date: "18 December 2024", photo: gdrive("1FRjrTsW6sGTS27dXMnqx9_bE4ExO26J8"), caption: "Every day a new discovery and a new wonder", milestone: "Imagination blooms", ageInDays: 968, location: "কাফরুল, ঢাকা" },
  { label: "2y 8m", age: "2 yr 8 mo", date: "26 December 2024", photo: gdrive("1fEf87Qhn141cuPXkmk1zHyBsnTusCX9e"), caption: "Every day a new discovery and a new wonder", milestone: "Imagination blooms", ageInDays: 976, location: "মিরপুর সেনানিবাস, ঢাকা" },
  { label: "2y 8m", age: "2 yr 8 mo", date: "12 January 2025", photo: gdrive("17siizyrYh1f20SLV00hLDJmjjSjwTlW_"), caption: "Every day a new discovery and a new wonder", milestone: "Imagination blooms", ageInDays: 993, location: "হাজারীবাগ, ঢাকা" },
  { label: "2y 10m", age: "2 yr 10 mo", date: "22 February 2025", photo: gdrive("1LmlX5TpGV6jsIPu7PTa_t2o6FQsx5-lf"), caption: "Every day a new discovery and a new wonder", milestone: "Imagination blooms", ageInDays: 1034, location: "কাফরুল, ঢাকা" },
  { label: "2y 10m", age: "2 yr 10 mo", date: "15 March 2025", photo: gdrive("1S6gkyRDt6tDQO2g5XKcdiBD_97ANZavE"), caption: "Every day a new discovery and a new wonder", milestone: "Imagination blooms", ageInDays: 1055, location: "হাজারীবাগ, ঢাকা" },
  { label: "2y 11m", age: "2 yr 11 mo", date: "2 April 2025", photo: gdrive("1aKBGl0c4sXpl1Xu-umxxbeZorWtjNSbQ"), caption: "Every day a new discovery and a new wonder", milestone: "Imagination blooms", ageInDays: 1073, location: "কাজীপাড়া, ঢাকা" },
  { label: "2y 12m", age: "2 yr 12 mo", date: "22 April 2025", photo: gdrive("13Jv-aX0TW0CP89lz_HTFHgQ5nXioAjYZ"), caption: "Every day a new discovery and a new wonder", milestone: "Imagination blooms", ageInDays: 1093, location: "হাজারীবাগ, ঢাকা" },
  { label: "2y 12m", age: "2 yr 12 mo", date: "22 April 2025", photo: gdrive("1mJPiUtbZ9R7GR19-VUIIeBbjQm4br1R0"), caption: "Every day a new discovery and a new wonder", milestone: "Imagination blooms", ageInDays: 1093, location: "হাজারীবাগ, ঢাকা" },
  { label: "2y 12m", age: "2 yr 12 mo", date: "23 April 2025", photo: gdrive("1FLK95EVJ9ZVZjhQQS8Q5UDGMQHfIAe6w"), caption: "Every day a new discovery and a new wonder", milestone: "Imagination blooms", ageInDays: 1094, location: "হাজারীবাগ, ঢাকা" },
  { label: "3yr", age: "3 years", date: "26 April 2025", photo: gdrive("1q0Qqvu-ykOiQ6QADs6DA64OxKPK84WuX"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1097, location: "বসুন্ধরা আবাসিক এলাকা, ঢাকা" },
  { label: "3yr", age: "3 years", date: "26 April 2025", photo: gdrive("1Wm3uXhM3JYK75UavnwoKZdeiWfNXpDfg"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1097, location: "বসুন্ধরা আবাসিক এলাকা, ঢাকা" },
  { label: "3yr", age: "3 years", date: "28 April 2025", photo: gdrive("1tBaigPg0i8v1Q3JeENWgkZVMn52I5uao"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1099, location: "বসুন্ধরা আবাসিক এলাকা, ঢাকা" },
  { label: "3yr", age: "3 years", date: "28 April 2025", photo: gdrive("14GrvThuvejy1KVMp7HrBsuX4xmItj0eR"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1099, location: "বসুন্ধরা আবাসিক এলাকা, ঢাকা" },
  { label: "3yr", age: "3 years", date: "29 April 2025", photo: gdrive("1aB7bS-WmlrRKsY37W3kGD6JwzvpzUeRA"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1100, location: "বসুন্ধরা আবাসিক এলাকা, ঢাকা" },
  { label: "3y 1m", age: "3 yr 1 mo", date: "10 May 2025", photo: gdrive("1tZtGPpwCMuHF4vVTe2Z7uw8Hzb1VMk8c"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1111, location: "কাজীপাড়া, ঢাকা" },
  { label: "3y 1m", age: "3 yr 1 mo", date: "25 May 2025", photo: gdrive("1aMDaCa_8d4YD1lwB3SteT3rLpbCxHzUI"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1126, location: "গুলশান, ঢাকা" },
  { label: "3y 1m", age: "3 yr 1 mo", date: "11 June 2025", photo: gdrive("1lWZHplR0lMmDy1qA3zrxuFvqqQKw-OHk"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1143, location: "শ্রীপুর উপজেলা (গাজীপুর)" },
  { label: "3y 1m", age: "3 yr 1 mo", date: "16 June 2025", photo: gdrive("176IQVbmG6waeF28jjPtdKvBqjupRY8j7"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1148, location: "শ্রীপুর উপজেলা (গাজীপুর)" },
  { label: "3y 3m", age: "3 yr 3 mo", date: "10 July 2025", photo: gdrive("155dp-2RI86sIONlE0oBIUZrxxVQI4tKr"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1172, location: "কাফরুল, ঢাকা" },
  { label: "3y 3m", age: "3 yr 3 mo", date: "20 July 2025", photo: gdrive("1-N-rOXLg3ev7SdsbPnTWK81s_AqaW6ul"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1182, location: "আদাবর, ঢাকা" },
  { label: "3y 3m", age: "3 yr 3 mo", date: "2 August 2025", photo: gdrive("1q9ynulYeMGbUftQWuLR7_5tpd_ch7ohH"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1195, location: "কাফরুল, ঢাকা" },
  { label: "3y 3m", age: "3 yr 3 mo", date: "11 August 2025", photo: gdrive("1QJYXzkLpajhvcsmoT0vLyI9bzBmQQJ-e"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1204, location: "কাফরুল, ঢাকা" },
  { label: "3y 3m", age: "3 yr 3 mo", date: "18 August 2025", photo: gdrive("19DmRtb01XrJ842AaajtDyf8vLvQwJ9d8"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1211, location: "নাখালপাড়া, ঢাকা" },
  { label: "3y 3m", age: "3 yr 3 mo", date: "19 August 2025", photo: gdrive("1QPyP2rppe2Fb-SCUCQgWoV3ODGaSxLHE"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1212, location: "নাখালপাড়া, ঢাকা" },
  { label: "3y 4m", age: "3 yr 4 mo", date: "11 September 2025", photo: gdrive("1afVFPtUSotdVgs86rzZ1G_HIN5ghUsBM"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1235, location: "হাজারীবাগ, ঢাকা" },
  { label: "3y 5m", age: "3 yr 5 mo", date: "21 September 2025", photo: gdrive("1B2_9inucE4JmSyjWH3Sx8_bwM4kw6zWZ"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1245, location: "কল্যাণপুর, ঢাকা" },
  { label: "3y 5m", age: "3 yr 5 mo", date: "22 September 2025", photo: gdrive("1ycG4N0EgIcABmoQ8aOPNDBnTLQmFbz3x"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1246, location: "আদাবর, ঢাকা" },
  { label: "3y 5m", age: "3 yr 5 mo", date: "27 September 2025", photo: gdrive("118_KUXCj-h2hsajWbB7ye6dGbocmNuMy"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1251, location: "কাফরুল, ঢাকা" },
  { label: "3y 5m", age: "3 yr 5 mo", date: "9 October 2025", photo: gdrive("1yScgm8V8OzKfT_ml77izYVDvsnZV1H6e"), caption: "Mama and baba's biggest pride and joy", milestone: "Preschool days", ageInDays: 1263, location: "কাফরুল, ঢাকা" },
  { label: "3y 6m", age: "3 yr 6 mo", date: "1 November 2025", photo: gdrive("1gTU896cUT73yWUoGxdqbsjwVT65kc7vC"), caption: "Getting bigger, brighter, and more beautiful every day", milestone: "Growing up fast", ageInDays: 1286, location: "জিগাতলা, ঢাকা" },
  { label: "3y 6m", age: "3 yr 6 mo", date: "18 November 2025", photo: gdrive("1PD39IKjHvd831KPEeuM_P3Dg4PUDdgVP"), caption: "Getting bigger, brighter, and more beautiful every day", milestone: "Growing up fast", ageInDays: 1303, location: "পিলখানা, ঢাকা" },
  { label: "3y 7m", age: "3 yr 7 mo", date: "23 November 2025", photo: gdrive("1AJkSjx4NKObc-uNr1hGFKy15RpDV3-3U"), caption: "Getting bigger, brighter, and more beautiful every day", milestone: "Growing up fast", ageInDays: 1308 },
  { label: "3y 8m", age: "3 yr 8 mo", date: "30 December 2025", photo: gdrive("1iPazcAGo3h4I-4y7t3PBAd-nrh8nu05o"), caption: "Getting bigger, brighter, and more beautiful every day", milestone: "Growing up fast", ageInDays: 1345, location: "কল্যাণপুর, ঢাকা" },
  { label: "3y 8m", age: "3 yr 8 mo", date: "3 January 2026", photo: gdrive("1CBJzb6HwgOAeQfVWpNinxfuribzfELeV"), caption: "Getting bigger, brighter, and more beautiful every day", milestone: "Growing up fast", ageInDays: 1349, location: "কল্যাণপুর, ঢাকা" },
  { label: "3y 8m", age: "3 yr 8 mo", date: "3 January 2026", photo: gdrive("11Y_SN0sVjrDHdr-6kZIzWzIla6SMh_0S"), caption: "Getting bigger, brighter, and more beautiful every day", milestone: "Growing up fast", ageInDays: 1349, location: "কল্যাণপুর, ঢাকা" },
  { label: "3y 8m", age: "3 yr 8 mo", date: "8 January 2026", photo: gdrive("1HcoP-ezlvUBPT8fsltZSEr5YJJuibgt0"), caption: "Getting bigger, brighter, and more beautiful every day", milestone: "Growing up fast", ageInDays: 1354, location: "কাফরুল, ঢাকা" },
  { label: "3y 8m", age: "3 yr 8 mo", date: "10 January 2026", photo: gdrive("1k4hV35KesB5o4NsIstGQuMzFk-Ui5BzM"), caption: "Getting bigger, brighter, and more beautiful every day", milestone: "Growing up fast", ageInDays: 1356, location: "কল্যাণপুর, ঢাকা" },
  { label: "3y 8m", age: "3 yr 8 mo", date: "10 January 2026", photo: gdrive("1XYGo8a2pRVkel5yi6KPzntrj6po3t1ZU"), caption: "Getting bigger, brighter, and more beautiful every day", milestone: "Growing up fast", ageInDays: 1356, location: "কল্যাণপুর, ঢাকা" },
  { label: "3y 9m", age: "3 yr 9 mo", date: "4 February 2026", photo: gdrive("1nte2KiwRTofttFj_jSPhBuTHwf1BjIBY"), caption: "Getting bigger, brighter, and more beautiful every day", milestone: "Growing up fast", ageInDays: 1381, location: "গুলশান, ঢাকা" },
  { label: "3y 10m", age: "3 yr 10 mo", date: "13 March 2026", photo: gdrive("1UxLvUdt5pPMuJpx6Zc8Lta5z180byiOr"), caption: "Getting bigger, brighter, and more beautiful every day", milestone: "Growing up fast", ageInDays: 1418, location: "পীরেরবাগ, ঢাকা" },
  { label: "3y 11m", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1wySgALkD5y4VXKhtQYclZgTTiBJK35je"), caption: "Celebrating Pahela Boishakh with family!", milestone: "Pahela Boishakh", ageInDays: 1450 },
  { label: "3y 11m", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1lzzo2xy3trXmPqKflpLv5uXKP4cNO-KY"), caption: "Celebrating Pahela Boishakh with family!", milestone: "Pahela Boishakh", ageInDays: 1450 },
  { label: "4yr", age: "4 years", date: "11 May 2026", photo: gdrive("1b2tnSWKq4jl8RuPkgt6EVyCmYf4E9mlX"), caption: "A magical day out with family!", milestone: "Family adventures", ageInDays: 1477 },
  { label: "4yr", age: "4 years", date: "11 May 2026", photo: gdrive("1rDY7Hu2JvOokhERcJ5Ud146q4KyJ2XkL"), caption: "A magical day out with family!", milestone: "Family adventures", ageInDays: 1477 },
  { label: "4y 1m", age: "4 yr 1 mo", date: "11 June 2026", photo: gdrive("1P3QiEmpilafVWIRCkatuTkpfeqSn_6WV"), caption: "Getting bigger, brighter, and more beautiful every day", milestone: "Growing up fast", ageInDays: 1508, location: "হাজারীবাগ, ঢাকা" },
  { label: "4y 1m", age: "4 yr 1 mo", date: "13 June 2026", photo: gdrive("1emVucLUM1ibM3TPKsv1PTHHvUHEPzq6W"), caption: "Getting bigger, brighter, and more beautiful every day", milestone: "Growing up fast", ageInDays: 1510, location: "হাজারীবাগ, ঢাকা" },
  { label: "4y 1m", age: "4 yr 1 mo", date: "13 June 2026", photo: gdrive("1KBCrE34Gy2k6ZV0N20S1EioDBE9uk4Bs"), caption: "Getting bigger, brighter, and more beautiful every day", milestone: "Growing up fast", ageInDays: 1510, location: "হাজারীবাগ, ঢাকা" },
  { label: "4y 1m", age: "4 yr 1 mo", date: "14 June 2026", photo: gdrive("194S1y8FcqTDmnSvfv0e4TdlJuWt0sgdP"), caption: "Getting bigger, brighter, and more beautiful every day", milestone: "Growing up fast", ageInDays: 1511, location: "হাজারীবাগ, ঢাকা" },
  { label: "4y 1m", age: "4 yr 1 mo", date: "21 June 2026", photo: gdrive("1jxhClo1TvywQeA6T3mYgPypIuhBKVpxU"), caption: "Getting bigger, brighter, and more beautiful every day", milestone: "Growing up fast", ageInDays: 1518, location: "পাইকড়া, কালিহাতী উপজেলা" },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("10ALNwphBNXgT3o0r4Tr-5cjH5o95Ogd5"), caption: "Celebrating Pahela Boishakh with family! 🌺", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("11RyaEe621pXV9lkZXqJdlcBNLifxpoUI"), caption: "পহেলা বৈশাখ — বাংলা নববর্ষ ১৪৩৩ 🎉", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1iFoACDgKvPp-w77JGUI9Eb2o0kq0lXZ7"), caption: "Dressed in red and white for the Bengali New Year! 🌸", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("17R-62-L8hW6ezJd5tGIbB5fKaysGVUl9"), caption: "The joy of বৈশাখ fills every moment 💛", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("14jIht3Xun_L0V6HiCzxc4sFb8g56q-5O"), caption: "Creating beautiful New Year memories together 🌼", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1F2alQYeu-EcyPSpjkfW0infANWLtxnUH"), caption: "পহেলা বৈশাখের আনন্দ ✨", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1cfA_I2pjxmJ0BLIgSCK-v1JD3mJ-tDQt"), caption: "Shubho Noboborsho! 🌟 Alysha rings in the New Year", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1W9Qd4DP71XXJrOK4GsCoj72c1SdX3qaL"), caption: "Boishakh festival fun with the whole family 🥰", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1WkRl1ROqyPKSypmsFXZkf24Z9h8iPoNw"), caption: "Celebrating Pahela Boishakh with family! 🌺", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1RwrmFEp4U3B8sA2d8vSDHpd-2Pura5Ui"), caption: "পহেলা বৈশাখ — বাংলা নববর্ষ ১৪৩৩ 🎉", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1gfndtbyLf73kAEgiCCVvHl8YDkXwM3YA"), caption: "Dressed in red and white for the Bengali New Year! 🌸", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1s0eBy_eL5eakZXnEOd2uSKUef83AOPjL"), caption: "The joy of বৈশাখ fills every moment 💛", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1BMhGGAO_iMEISUX69cbVkddlkNnq1J3M"), caption: "Creating beautiful New Year memories together 🌼", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1NYuDOIBppq0CnsiL3mx04fj-lMhsjAC_"), caption: "পহেলা বৈশাখের আনন্দ ✨", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1vgNIEC8V8XWI1pFYjB1oP5WkMM-opk0F"), caption: "Shubho Noboborsho! 🌟 Alysha rings in the New Year", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1X0a5M_eIXG8w403E3tTU08Ym4hx_rRTr"), caption: "Boishakh festival fun with the whole family 🥰", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1m54NvE1m9Sst-3bPN24f4_m_hhbpX6qN"), caption: "Celebrating Pahela Boishakh with family! 🌺", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1q9YuBD_YKYwnwg3SMN0ILhYXJJjj6J3K"), caption: "পহেলা বৈশাখ — বাংলা নববর্ষ ১৪৩৩ 🎉", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1dHWIwVs-YhOMBe2xFdBEawERKC4InWoa"), caption: "Dressed in red and white for the Bengali New Year! 🌸", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1OoqtUGI7h93bgxNtVENqB1oZglxgK2Eo"), caption: "The joy of বৈশাখ fills every moment 💛", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("11P4N1Oglph47JbuEEq48nGxI3DIMturX"), caption: "Creating beautiful New Year memories together 🌼", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1GglQJhpeZ8tDhUxSie0DW6-M6WkGMqjs"), caption: "পহেলা বৈশাখের আনন্দ ✨", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1oZJLGSiREJNqGjt2JZWpl7y1qAlVCt-f"), caption: "Shubho Noboborsho! 🌟 Alysha rings in the New Year", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1RnWXVHaIWAHSqFgBpDkRUFJUloyrst27"), caption: "Boishakh festival fun with the whole family 🥰", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1tSh-vDQyb8JXjs1RTAyFFzo7sh5WfpyC"), caption: "Celebrating Pahela Boishakh with family! 🌺", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("12Dd5lFGlsp8cSX4OLiZzt_w_t6910yYv"), caption: "পহেলা বৈশাখ — বাংলা নববর্ষ ১৪৩৩ 🎉", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1yLy0n5Nh5jNpf-FywgmOoeioghOKZT34"), caption: "Dressed in red and white for the Bengali New Year! 🌸", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1v2sq0wZM1kpk4GAuHRHFKz6EE4dLHmzi"), caption: "The joy of বৈশাখ fills every moment 💛", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1jXFrHP02bJrU25F71p_a41Ju3xLouKG1"), caption: "Creating beautiful New Year memories together 🌼", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("15HrCSdLMi0STrONymghPy5__uzP0bCu2"), caption: "পহেলা বৈশাখের আনন্দ ✨", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1xE4XcftEoZpM3F6sRVodl6E0n5cHif9g"), caption: "Shubho Noboborsho! 🌟 Alysha rings in the New Year", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1CJk8gd13o8qEIaHqjtpy67OQcFRbxRUv"), caption: "Boishakh festival fun with the whole family 🥰", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1PzKg_kmaIIYesj7TkmLj1RvrxQjR4hdi"), caption: "Celebrating Pahela Boishakh with family! 🌺", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1CJxSAlctBTt342pQUGilUhglimp4jb_6"), caption: "পহেলা বৈশাখ — বাংলা নববর্ষ ১৪৩৩ 🎉", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1D54svR58Zu_H5kqgW_FUmLqZ57q5Z68R"), caption: "Dressed in red and white for the Bengali New Year! 🌸", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("19o3Zy_506NbYQMwe_cfHCIHgeeYJCHEu"), caption: "The joy of বৈশাখ fills every moment 💛", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1T16j-0hZMuGWXhaCMkMZJU4ShcQLQRB-"), caption: "Creating beautiful New Year memories together 🌼", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("14HrsS9xRpcy7w3cSzZXfmrkBSn_11Nf9"), caption: "পহেলা বৈশাখের আনন্দ ✨", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("19P57t1733Uys_BpRemECSCFYUwyoMomk"), caption: "Shubho Noboborsho! 🌟 Alysha rings in the New Year", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1UZtOj9G9gEPMxc6dUMCc_leFCq3Dxvpx"), caption: "Boishakh festival fun with the whole family 🥰", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1xhGoVJDxS0Ip3PkPIcoxCyqlzl2UqgkX"), caption: "Celebrating Pahela Boishakh with family! 🌺", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1QvD4SVZravgp4v5eIF_yLxuo0wOh_0aB"), caption: "পহেলা বৈশাখ — বাংলা নববর্ষ ১৪৩৩ 🎉", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1YlZyJMqWulcMJW1DtIFpmCDCq35zFcvC"), caption: "Dressed in red and white for the Bengali New Year! 🌸", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1yaaisiI9I-pZdgWc_PwmIcg2H3csxp5U"), caption: "The joy of বৈশাখ fills every moment 💛", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1VS1yBs0HrSF9ctaI8cCgl_XRBDKy6o7t"), caption: "Creating beautiful New Year memories together 🌼", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1vt1dx1QWOXaDUtj5VCul1ozqJ5HzMoPa"), caption: "পহেলা বৈশাখের আনন্দ ✨", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1R3WM3xXNB3lO30UE9z1RqShSmS-pifnO"), caption: "Shubho Noboborsho! 🌟 Alysha rings in the New Year", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("18yiSIoe1w0czQ0j3qgjWAmWcnpH5DCcB"), caption: "Boishakh festival fun with the whole family 🥰", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("10ZdnBY1PLmfJzmv6IZwupKmoZW9__72O"), caption: "Celebrating Pahela Boishakh with family! 🌺", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1XtXLKOdcvk2MVloJTmR7Zte390INQEvg"), caption: "পহেলা বৈশাখ — বাংলা নববর্ষ ১৪৩৩ 🎉", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1WLGziCFyO6XntT_laLX62U3ychmB1mxW"), caption: "Dressed in red and white for the Bengali New Year! 🌸", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1DDD57ixoOOLotsv17u0L3oLiNVkhmo06"), caption: "The joy of বৈশাখ fills every moment 💛", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1cHXFcRQs71lDWPeOBbRgeAxY7nWw81w3"), caption: "Creating beautiful New Year memories together 🌼", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1BRqLEWbGOdSLIj00efRdwk_5eroeXaGe"), caption: "পহেলা বৈশাখের আনন্দ ✨", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("173Z4cUgbceKgldrAx6gJFLMBibsRWPFy"), caption: "Shubho Noboborsho! 🌟 Alysha rings in the New Year", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1HahKzX7ImprImY-oWE5SxsvrsNCs6V9d"), caption: "Boishakh festival fun with the whole family 🥰", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1P_nIk0tncP5V3Qo5t4YMh9XVrXrOhZWo"), caption: "Celebrating Pahela Boishakh with family! 🌺", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1cn1icS01Ny8UsjOye33pdlwHLOcZb2oa"), caption: "পহেলা বৈশাখ — বাংলা নববর্ষ ১৪৩৩ 🎉", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1YFNLuVjTkfE23FJxxwzJfvYMf8TreJpP"), caption: "Dressed in red and white for the Bengali New Year! 🌸", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("18slAETTT7LXR_4hkqyX6ZV2URwK4FW1g"), caption: "The joy of বৈশাখ fills every moment 💛", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1tcROpO751YtpRRr4160aNkBEbl7aDtrn"), caption: "Creating beautiful New Year memories together 🌼", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1akUvuSZvUQ7Ke2g4G_NJ2KZFlcU9l-T3"), caption: "পহেলা বৈশাখের আনন্দ ✨", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1SybbCaBDqzJdR6yvwnSCV1RtDbDQvlpK"), caption: "Shubho Noboborsho! 🌟 Alysha rings in the New Year", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1JJyjcbpLxmLS10Tl5mIPYmLfxn8Gt7yj"), caption: "Boishakh festival fun with the whole family 🥰", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1q6kvzsl6uGzFy1dICHVjHuBzkzywBa2V"), caption: "Celebrating Pahela Boishakh with family! 🌺", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1O2pNni0cADGZNrsdCnU6KkfUJZ3ZOgN5"), caption: "পহেলা বৈশাখ — বাংলা নববর্ষ ১৪৩৩ 🎉", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1AwTwIBGICtBCEK_spdMGXuMuLmGZcqtb"), caption: "Dressed in red and white for the Bengali New Year! 🌸", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1kz4bDHf7ij9afvjmFswl66aiHUJE2wsM"), caption: "The joy of বৈশাখ fills every moment 💛", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1L4eAnu9Mi1VvmfSNtxCGL4ntC4LiudLI"), caption: "Creating beautiful New Year memories together 🌼", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("10fSenlirVqWS2I1ZdjFzbwY2EzfXTRHg"), caption: "পহেলা বৈশাখের আনন্দ ✨", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1YN-xXgrU3YDgnLYcC6agvcP2Tpvv8kGS"), caption: "Shubho Noboborsho! 🌟 Alysha rings in the New Year", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1MFLXrZp_PBXzbC33F3kljrP4kHYoVVdG"), caption: "Boishakh festival fun with the whole family 🥰", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1IKZ47SEg8hufMWYlcU_FflAaZZJPxfxX"), caption: "Celebrating Pahela Boishakh with family! 🌺", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1jaUG0KpHV1IaR-rZLGVjLcJ4qbi-kkG9"), caption: "পহেলা বৈশাখ — বাংলা নববর্ষ ১৪৩৩ 🎉", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("16BbwXJejMTLcxj6CuytzrxgDOZJsf-U5"), caption: "Dressed in red and white for the Bengali New Year! 🌸", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1KkHuQ-G8PuTUE-2G0i2UkoxtOef_pEgS"), caption: "The joy of বৈশাখ fills every moment 💛", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("15rOBCDeLhT2kN0kWTnlgMOmgwJO62SvH"), caption: "Creating beautiful New Year memories together 🌼", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("12b6PrXtRnxdPBN_xSCOjty-QHSuwSOP4"), caption: "পহেলা বৈশাখের আনন্দ ✨", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1CUHF34IT8aXxRKP2BeyCjBB0jg8HaXjF"), caption: "Shubho Noboborsho! 🌟 Alysha rings in the New Year", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1X54-6KXW89WuJsEvOr3TZ2LY_WmZq35P"), caption: "Boishakh festival fun with the whole family 🥰", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("12doGR4wN7LrXtpzIz4pGnlf-RrbJERSn"), caption: "Celebrating Pahela Boishakh with family! 🌺", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1-YfgP-cU0HAghJMrJWaoEOoEeQ_LCRDx"), caption: "পহেলা বৈশাখ — বাংলা নববর্ষ ১৪৩৩ 🎉", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("17hBAU6PFxNYilsus7toqMUqQZq_JWfKM"), caption: "Dressed in red and white for the Bengali New Year! 🌸", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1Bzv97TH79sH_1AJlIIRHXUHpBlGFxvWP"), caption: "The joy of বৈশাখ fills every moment 💛", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1UfTc9u-jKfs8Ze6hz6jPHu9ovxNVPLe5"), caption: "Creating beautiful New Year memories together 🌼", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1xv5c7J7cWsyAw5eEAGAeXctgWdlG0rny"), caption: "পহেলা বৈশাখের আনন্দ ✨", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1VzD7l8DuKJ-IbW8U2SvyQ0kjtYdxUx9s"), caption: "Shubho Noboborsho! 🌟 Alysha rings in the New Year", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1SYm921oI-Js9ujClU4Q2jQkPW3_HXWW4"), caption: "Boishakh festival fun with the whole family 🥰", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1HuY31wmq8DzvNTJIvBqcm-nQksx-M40u"), caption: "Celebrating Pahela Boishakh with family! 🌺", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1cQcLmCGz8z7uu7i8XKXFzpjA5hc6nl4U"), caption: "পহেলা বৈশাখ — বাংলা নববর্ষ ১৪৩৩ 🎉", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1tHurp7_XEjuV3Rc74kklgIZXtetwdS0e"), caption: "Dressed in red and white for the Bengali New Year! 🌸", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1rbjqFU4k2_qsWvfO_c3bMl79YVf0XXyT"), caption: "The joy of বৈশাখ fills every moment 💛", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1Zg3r0qiWh1wEHm-65PYoBdIYPy7KqHpW"), caption: "Creating beautiful New Year memories together 🌼", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1E6mN9tHU5VT8sPFq3wumPpvFEcQHkLwe"), caption: "পহেলা বৈশাখের আনন্দ ✨", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1Eas3nm4eECdgpIabP1-FOd9OAmq2ujEp"), caption: "Shubho Noboborsho! 🌟 Alysha rings in the New Year", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1dDtia8Jc-195vRk3akiUnIEXaSI7VYni"), caption: "Boishakh festival fun with the whole family 🥰", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1jL3bG2wQ9zVNHj6WISS8lJ1KdiHSyxlV"), caption: "Celebrating Pahela Boishakh with family! 🌺", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("11di-xwZv8CpLuZKIsSFoFO4_xvGabLMQ"), caption: "পহেলা বৈশাখ — বাংলা নববর্ষ ১৪৩৩ 🎉", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1qLL1caraas2B9ntx0Atlt1rJfZC2ypEN"), caption: "Dressed in red and white for the Bengali New Year! 🌸", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("13OwmEcm-ViLz5qf56pe5VDqZ-CfvkWpx"), caption: "The joy of বৈশাখ fills every moment 💛", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1e5PW8nhgBesmfDN1Q14pEdu_t7RNi-y8"), caption: "Creating beautiful New Year memories together 🌼", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("19Vfrwh2xAIy0m1qIX6ykfoamAexHtuxD"), caption: "পহেলা বৈশাখের আনন্দ ✨", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1JvCPhR0EcVlBC-PFsYniiPdkHebSWSgS"), caption: "Shubho Noboborsho! 🌟 Alysha rings in the New Year", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1W-ERSYFXRcesVHr1jeqAZyIefk34RcAB"), caption: "Boishakh festival fun with the whole family 🥰", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1CWYZGI775t9Q8_A2Z2tFAo1_A0seR4Yc"), caption: "Celebrating Pahela Boishakh with family! 🌺", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1zqX3SPJaX2A-o82cZXB8768Qsp5zHgzq"), caption: "পহেলা বৈশাখ — বাংলা নববর্ষ ১৪৩৩ 🎉", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1j1aio1572wDBdKAChzdN-4q5DZZ2hTDf"), caption: "Dressed in red and white for the Bengali New Year! 🌸", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1nQRbyjJeZ6lZ4CDH2hdUQizfj3FdIqIg"), caption: "The joy of বৈশাখ fills every moment 💛", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1eeReMrP2hqIEXOdiir3SlyKOh8aN5b0o"), caption: "Creating beautiful New Year memories together 🌼", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1U7yzQ-Ohb22RIzQjucifRnvfaffhuBcs"), caption: "পহেলা বৈশাখের আনন্দ ✨", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1uIbwSkwH9puwQ10xEO2JnaHueeXsdm0l"), caption: "Shubho Noboborsho! 🌟 Alysha rings in the New Year", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1p3n9CnsfYwGzTupD0hqRY3QpLr_ygliA"), caption: "Boishakh festival fun with the whole family 🥰", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1TM-I1gHRzRESt97n2cC6pnUjlFvV8bAc"), caption: "Celebrating Pahela Boishakh with family! 🌺", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1834ECOgr91nY_hvqy52XQdxFGEjW5tXf"), caption: "পহেলা বৈশাখ — বাংলা নববর্ষ ১৪৩৩ 🎉", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1Ho0ImltAmCplu5kg8WIhVe2e05gXw2VM"), caption: "Dressed in red and white for the Bengali New Year! 🌸", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("16UHNp0bErmBywGsmSM9CHseUN53XPAOc"), caption: "The joy of বৈশাখ fills every moment 💛", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("17S5A9z3Zp_h4VsfJ8mlY5x96dDRv3CiH"), caption: "Creating beautiful New Year memories together 🌼", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1fDpqfdW1pFFpjDiG-HWYJby2kk0gYvH_"), caption: "পহেলা বৈশাখের আনন্দ ✨", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1vmD4ArElstykk6wPixkUDVsEfszhU3L2"), caption: "Shubho Noboborsho! 🌟 Alysha rings in the New Year", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1Rrb8ZqTKI55QrQR9W-I1gr_gpyFwn-FK"), caption: "Boishakh festival fun with the whole family 🥰", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1zAZw_QSuJh3qt9lLQLEKeXJ86UyRqOzG"), caption: "Celebrating Pahela Boishakh with family! 🌺", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("167URYTD-dZx3a_BZEQJPbXIJo19nwFIl"), caption: "পহেলা বৈশাখ — বাংলা নববর্ষ ১৪৩৩ 🎉", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("17vEcdxhjBcxWScfy9ISd9i64gVknldMK"), caption: "Dressed in red and white for the Bengali New Year! 🌸", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1SPzowGpy6cw9L9zbi1yhromAwPYrIvQF"), caption: "The joy of বৈশাখ fills every moment 💛", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1n1nKLx97yjU6u93CIB7j4yiv0tnfs-p7"), caption: "Creating beautiful New Year memories together 🌼", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("15_ufuKH9kdtBbK8oODC3SlkMCqnVNZNb"), caption: "পহেলা বৈশাখের আনন্দ ✨", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1kF9J9Rqc-xqj_HvQAcPDC39H9t9JaHzo"), caption: "Shubho Noboborsho! 🌟 Alysha rings in the New Year", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1TYVusDnNdsfPzSg6_B315bgHkzdklqSb"), caption: "Boishakh festival fun with the whole family 🥰", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1BIatcBvOaT9-RMoFJap0NEkt-B52niG2"), caption: "Celebrating Pahela Boishakh with family! 🌺", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1aLWOT_8TykqvLTOLzSZWraTLooxtUcaR"), caption: "পহেলা বৈশাখ — বাংলা নববর্ষ ১৪৩৩ 🎉", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("1fNYKw6MlJ3tG3-Y-GgIveCZA4vzFalKN"), caption: "Dressed in red and white for the Bengali New Year! 🌸", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "পহেলা বৈশাখ", age: "3 yr 11 mo", date: "14 April 2026", photo: gdrive("14ZxetzaiOgvD_PxACdxhY-3NzUPpNeen"), caption: "The joy of বৈশাখ fills every moment 💛", milestone: "Pahela Boishakh 2026", ageInDays: 1450 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1zQMNq2cVKc-MEivYu9HnEMtqyt_uZT2y"), caption: "A magical day out with family! 🌟", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1gr-ROSLOW181U-l1y0V6JJ1rdPgH1ZPd"), caption: "Adventures and smiles all around 😊", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1Xc-2ug3oa-fpemqjkL2-O_X9n7pAD3i-"), caption: "Exploring the world with curious eyes 🌍", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1tr_JVSHKkFkvJ57PW1Wyl0jzEGJpTmKa"), caption: "Making memories on our special day out 💕", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1ZplpoVdLgnfuKor1ue2AC6zVr8pQw6WM"), caption: "Sunshine, laughter, and endless fun ☀️", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1eTdaPU39BtvGiISoUusc7i_HGVEWGFZ4"), caption: "Every outing is an adventure with Alysha! 🎈", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1pCoBWwnJ6wzk1btfEihwn4L2v9NmFX9I"), caption: "Happy girl, happy day! 🎊", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1sNmVonz82ZLb3XQ37z7-7uCY5AnPAvOC"), caption: "Out and about, discovering the world 🚀", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1-Clbdo31TLmQcL04trw3AIJ2bKSOk8aa"), caption: "A magical day out with family! 🌟", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1rFSKcPys_Mk8GYdnNK25vcZHQhue3mcs"), caption: "Adventures and smiles all around 😊", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1C04s2JGsCyNueqzyMGp9c2tNXb9_b0Gf"), caption: "Exploring the world with curious eyes 🌍", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1M4ir8GUwcxFZCGzXWpcKoGY1TASd-ywd"), caption: "Making memories on our special day out 💕", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1t0aphT3S9ZqhKBqZKrfJ_3iOTJMQsceb"), caption: "Sunshine, laughter, and endless fun ☀️", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1EXFxeQGovdxRTjF-a57j2n3GoJoN8Az0"), caption: "Every outing is an adventure with Alysha! 🎈", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1xEkLBzDpEkIjqEX5nnI-HbEZXXQerNbm"), caption: "Happy girl, happy day! 🎊", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1GPiVLCrKNsBLGRvtKU9AZR5K47rW62tk"), caption: "Out and about, discovering the world 🚀", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1JdwMhcG8jSpqFbpsGqn2hAQEMFLyOd8s"), caption: "A magical day out with family! 🌟", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("12IKi9n8WwdBX-01pcRMtA1NkLlAm1Y3Y"), caption: "Adventures and smiles all around 😊", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1Ua4iMy7JZtXfxtjKU-R2ZQJRasYzZ38f"), caption: "Exploring the world with curious eyes 🌍", milestone: "Family adventures", ageInDays: 1477 },
  { label: "Day Out", age: "4 years", date: "11 May 2026", photo: gdrive("1lyy8sy3otTL9ZXUWLAC96p9kKG4yVoRc"), caption: "Making memories on our special day out 💕", milestone: "Family adventures", ageInDays: 1477 },

];

function seed() {
  const adminEmail = process.env.ADMIN_EMAIL || "admin@alysha.family";
  const adminPassword = process.env.ADMIN_PASSWORD || "Alysha@2022";
  const existingAdmin = db.prepare("SELECT id FROM users WHERE email = ?").get(adminEmail);

  if (!existingAdmin) {
    const hash = bcrypt.hashSync(adminPassword, 12);
    db.prepare("INSERT INTO users (id, email, password, role) VALUES (?, ?, ?, ?)").run(
      uuidv4(), adminEmail, hash, "admin"
    );
    console.log(`✓ Admin user created: ${adminEmail}`);
  } else {
    console.log(`  Admin user already exists: ${adminEmail}`);
  }

  const count = db.prepare("SELECT COUNT(*) as n FROM entries").get().n;
  if (count > 0 && count !== ENTRIES.length) {
    // Re-seed when entry count has changed
    db.prepare("DELETE FROM entries").run();
    console.log(`  Cleared ${count} old entries — re-seeding with ${ENTRIES.length}`);
  } else if (count === ENTRIES.length) {
    console.log(`  Entries already seeded (${count} rows)`);
    return;
  }

  const insertEntry = db.prepare(
    `INSERT INTO entries (id, label, age, date, photo, caption, milestone, age_in_days, sort_order, location)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
  );
  const insertAll = db.transaction((entries) => {
    entries.forEach((e, i) => {
      insertEntry.run(uuidv4(), e.label, e.age, e.date, e.photo, e.caption, e.milestone, e.ageInDays, i, e.location || null);
    });
  });
  insertAll(ENTRIES);
  console.log(`✓ Seeded ${ENTRIES.length} timeline entries`);
}

seed();
console.log("✓ Database ready");
